export const typographyCatalogIds = {
  TITLE_BASIC: 'title-basic',
  TITLE_LEVEL: 'title-level',
  TITLE_VARIANT: 'title-variant',
  TITLE_ITALIC: 'title-italic',
  TITLE_WEIGHT: 'title-weight',
  TITLE_REMOVE: 'title-remove',
  TITLE_ALIGNS: 'title-aligns',
  TITLE_UNDERLINE: 'title-underline',
  TITLE_API: 'title-api',
  PARAGRAPH_BASIC: 'paragraph-basic',
  PARAGRAPH_SIZE: 'paragraph-size',
  PARAGRAPH_LINE_HEIGHT: 'paragraph-line-height',
  PARAGRAPH_MARK: 'paragraph-mark',
  PARAGRAPH_STRONG: 'paragraph-strong',
  PARAGRAPH_WEIGHT: 'paragraph-weight',
  PARAGRAPH_VARIANT: 'paragraph-variant',
  PARAGRAPH_ITALIC: 'paragraph-italic',
  PARAGRAPH_REMOVE: 'paragraph-remove',
  PARAGRAPH_ALIGNS: 'paragraph-aligns',
  PARAGRAPH_UNDERLINE: 'paragraph-underline',
  PARAGRAPH_API: 'paragraph-api'
} as const